DROP TABLE IF EXISTS parking_spots;
DROP TABLE IF EXISTS parking_lots;
DROP TABLE IF EXISTS cars;

CREATE TABLE IF NOT EXISTS parking_lots (
	id SERIAL PRIMARY KEY,
	latitude DOUBLE PRECISION NOT NULL,
	longitude DOUBLE PRECISION NOT NULL,
	city TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cars (
	id TEXT NOT NULL PRIMARY KEY,
	manufacturer TEXT,
	model TEXT NOT NULL,
	color TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS parking_spots (
	car_id TEXT NOT NULL,
	parking_lot_id INT NOT NULL,
	latitude DOUBLE PRECISION NOT NULL,
	longitude DOUBLE PRECISION NOT NULL,
	FOREIGN KEY(car_id) REFERENCES cars(id) ON DELETE CASCADE,
	FOREIGN KEY(parking_lot_id) REFERENCES parking_lots(id) ON DELETE CASCADE
);
